<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY7BVhje\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY7BVhje/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY7BVhje.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY7BVhje\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY7BVhje\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y7BVhje',
    'container.build_id' => '215ffc3d',
    'container.build_time' => 1610227693,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY7BVhje');
